mysql:
    image: mysql
    environment:
        MYSQL_DATABASE: contao
        MYSQL_ROOT_PASSWORD: mypass
contao:
    image: comolo/contao-docker
    links: 
        - "mysql:mysql"
    ports:
        - "80:80"
